targets:
  $default:
    builders:
      mockito|mockBuilder:
        enabled: false
      freezed:
        generate_for:
          - lib/**.gen.dart
      json_serializable:
        generate_for:
          - lib/**.gen.dart
